### ISSUE TITLE
Unused variable warning

### ISSUE THREAD

**Issue by moderation** [circonus-labs/libcircllhist#51]
Using the latest commit release in Envoy Proxy generates the following warning. It does look like `i` is defined at https://github.com/circonus-labs/libcircllhist/blob/master/src/circllhist.c#L926 and not used.
```
external/com_github_circonus_labs_libcircllhist/src/circllhist.c:926:9: warning: unused variable 'i' [-Wunused-variable]
    int i;
        ^
1 warning generated.
```

**Comment by vasuraman11** [comment]
Removed, this was a orphaned variable declaration.
