### ISSUE TITLE
Unused variable warning

### ISSUE THREAD

**Issue by moderation** [circonus-labs/libcircllhist#52]
Using the latest commit release in Envoy Proxy generates the following warnings.

https://github.com/circonus-labs/libcircllhist/blob/master/src/circllhist.c#L1181
https://github.com/circonus-labs/libcircllhist/blob/master/src/circllhist.c#L1241

```
external/com_github_circonus_labs_libcircllhist/src/circllhist.c:1181:7: warning: unused variable 'i' [-Wunused-variable]
  int i, tgt_idx, src_idx;
      ^
external/com_github_circonus_labs_libcircllhist/src/circllhist.c:1241:7: warning: unused variable 'i' [-Wunused-variable]
  int i, tgt_idx, src_idx;
      ^
2 warnings generated.
```

**Comment by HeinrichHartmann** [comment]
Resolved in d34f2e8e3db03148e60c34e1d3c611aadb04d9df
