### ISSUE TITLE
Mismatch of the format specifier and variable type

### ISSUE THREAD

**Issue by danfe** [circonus-labs/libcircllhist#54]
When compiling `circllhist_print.c`, Clang emits the following warning due to mismatch of the format specifier and variable type.  This does not happen on 64-bit machines, because `size_t` is 64-bit long there and matches `uint64_t`, but on 32-bit it is not.
```
circllhist_print.c:28:49: warning: format specifies type 'size_t'
      (aka 'unsigned int') but the argument has type 'uint64_t' (aka
      'unsigned long long') [-Wformat]
        printf("%s\"%g\":%zu", i ? "," : "", v, vc);
                         ~~~                    ^~
                         %llu
1 warning generated.
```

**Comment by HeinrichHartmann** [comment]
Thanks for sending this in. I have a opened a PR with a fix here:
https://github.com/circonus-labs/libcircllhist/pull/55

Do you want to check if this works on your machine?
