### ISSUE TITLE
unable to run it in mac [need help]

### ISSUE THREAD

**Issue by tannaga** [circonus-labs/libcircllhist#58]
Hi,

I followed the instruction in the readme file but still I am unable to get it working in my mac.
I get the below error
```
libcircllhist.so was not found on your system.
Please install libcircllhist from: https://github.com/circonus-labs/libcircllhist/
```
I am debugging this further, but if there are any pointers it will be of great help.

**Comment by postwait** [comment]
What gave you that error message? Mac native software would use .dylib files and not .so.

**Comment by tannaga** [comment]
@postwait I am running it in the jupyter notebook. 
something like this 
```
# log linear histogram
from circllhist import Circllhist
h = Circllhist()
data=df['txTime']
for d in data:
    h.insert(d)
    
print(h.quantile(0.5))
print(h.quantile(0.9))
print(h.quantile(0.95))
print(h.quantile(0.99))
```
is there a way to make it work with .dylib file?

**Comment by postwait** [comment]
Did you build and install libcircllhist?

**Comment by tannaga** [comment]
Yes. I ran the below commands without any errors
````
autoconf
./configure
make
make install
```

**Comment by postwait** [comment]
what was the output of the `make install` command?

**Comment by tannaga** [comment]
- make install

    
               (cd src && /Library/Developer/CommandLineTools/usr/bin/make)
		Building version info from git
		    * version -> 18f1b97603757d5e65baefa65b90d6ec182e8a30
		    * symbolic -> branches/master
		    * version unchanged
		(cd src && /Library/Developer/CommandLineTools/usr/bin/make install DESTDIR=)
		../buildtools/mkinstalldirs /usr/local/bin
		/usr/bin/install -c -m 0755 circllhist_print /usr/local/bin/circllhist_print
		../buildtools/mkinstalldirs /usr/local/include
		for file in circllhist.h ; do \
				/usr/bin/install -c -m 0644 $file /usr/local/include/$file ; \
			done
		../buildtools/mkinstalldirs /usr/local/lib
		../buildtools/mkinstalldirs /usr/local/share/lua/5.1
		/usr/bin/install -c -m 0755 libcircllhist.0.0.1.dylib /usr/local/lib/libcircllhist.0.0.1.dylib
		/usr/bin/install -c -m 0755 libcircllhist.a /usr/local/lib/libcircllhist.a
		ln -sf libcircllhist.0.0.1.dylib /usr/local/lib/libcircllhist.dylib
		/usr/bin/install -c -m 0755 lua/ffi_libcircllhist.lua /usr/local/share/lua/5.1/

     ```

**Comment by postwait** [comment]
I don't know why pythyon would attempt to load a .so file, I'm unfamiliar with how that python binding works.  Can you try:

```
sudo ln -sf libcircllhist.0.0.1.dylib /usr/local/lib/libcircllhist.so
```

and see if your python start working.

**Comment by tannaga** [comment]
Awesome. that did work!!!
Thank you.. I appreciate it.
